sudo: required
dist: trusty
language: generic
compiler: gcc

install:
  - sudo add-apt-repository -y ppa:beineri/opt-qt551-trusty
  - sudo apt-get update
  - sudo apt-get -y install qt55base qt55declarative
  - sudo apt-get -y install qt55quickcontrols qt55graphicaleffects
  - sudo apt-get -y install qt55tools

script:
  - source /opt/qt55/bin/qt55-env.sh
  - qmake EntityManager.pro -r "CONFIG+=release c++11" -after "DESTDIR = `pwd`/build/linux-g++-64/x86_64/release" # "OBJECTS_DIR=`pwd`/obj" "MOC_DIR=`pwd`/moc" "UI_DIR=`pwd`/ui" "RCC_DIR=`pwd`/rcc"
  - make
  - sudo make install
  - make check
