language: cpp

os:
  - linux
#  - osx

env:
  - CONFIG=Release
  - CONFIG=Debug

install:
    - sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa &&
    sudo apt-get update &&
    sudo apt-get install qtbase5-dev libqt5sql5-mysql libqt5sql5-sqlite &&
    sudo apt-get install lcov odbcinst libmyodbc odbc-postgresql

script:
  -  qmake
    && make
    && make check

notifications:
  email: false
