language: cpp

os:
  - linux
#  - osx

env:
  - CONFIG=Release
  - CONFIG=Debug

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
      && sudo apt-add-repository -y ppa:beineri/opt-qt541
      && sudo apt-get -qq update
      && sudo apt-get -qq install gcc-5 libc6-i386 qt54tools qt54svg qt54webkit
      && export CXX="g++-5"
      && export CC="gcc-5"
      && export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
      ;
    else
         brew update
      && brew unlink cmake
      && brew install cmake
      && brew install qt5
      && chmod -R 755 /usr/local/opt/qt5/*
      ;
    fi

script:
  -  QMAKE
    && make -j 3
    && make check
