# AppVeyor build configuration
# http://www.appveyor.com/docs/build-configuration
os: unstable

install:
  - set QTDIR=C:\Qt\5.4\mingw491_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin
  - set RELEASE_PATH=appveyor\release

build_script:
  # using a header file without MemoryBarrier, that causes the build to fail
  - qmake CuteEntityManager.pro -r -spec win32-g++
#  - qmake QOwnNotes.pro -r -spec win32-g++ "CONFIG+=debug"
  - mingw32-make
  # creating the release path
  - md ..\%RELEASE_PATH%
  # copy the binary to our release path
  #- copy release\CuteEntityManager.dll ..\%RELEASE_PATH%
  #- cd ..\%RELEASE_PATH%
  # fetching dependencies of QT app
  # http://doc.qt.io/qt-5/windows-deployment.html
  #- windeployqt --release CuteEntityManager
  # this dll was missed by windeployqt
#  - copy ..\libwinpthread-1.dll . /y
  # this dll didn't work when released by windeployqt
#  - copy "..\libstdc++-6.dll" . /y

