#############################################################################
# Makefile for building: libCuteEntityManager.so.1.0.0
# Generated by qmake (3.0) (Qt 5.5.0)
# Project:  EntityManager.pro
# Template: lib
# Command: /usr/lib/qt/bin/qmake -o Makefile EntityManager.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DCUTE_ENTITY_MANAGER_LIBRARY -DQT_NO_DEBUG_OUTPUT -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -Wall -Wextra -Wunsafe-loop-optimizations -pedantic -Wfloat-equal -Wundef -Wpointer-arith -Wcast-align -Wunreachable-code -O -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -std=c++1y -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/qt -isystem /usr/include/qt/QtSql -isystem /usr/include/qt/QtCore -I. -I/usr/lib/qt/mkspecs/linux-g++
QMAKE         = /usr/lib/qt/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = CuteEntityManager1.0.0
DISTDIR = /home/cehringfeld/gitrepos/entitymanager/.tmp/CuteEntityManager1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-O1,--sort-common,--as-needed,-z,relro -shared -Wl,-soname,libCuteEntityManager.so.1
LIBS          = $(SUBLIBS) -lsqlite3 -lQt5Sql -lQt5Core -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/entity.cpp \
		src/entitymanager.cpp \
		src/database.cpp \
		src/schema.cpp \
		src/schema/sqliteschema.cpp \
		src/tableschema.cpp \
		src/schema/pgsqlschema.cpp \
		src/schema/mysqlschema.cpp \
		src/databasemigration.cpp \
		src/querybuilder.cpp \
		src/schema/sqlitequerybuilder.cpp \
		src/relation.cpp \
		src/entityinstancefactory.cpp \
		src/cache.cpp \
		src/entityhelper.cpp \
		src/logger.cpp \
		src/query.cpp \
		src/join.cpp \
		src/queryinterpreter.cpp \
		src/expression.cpp \
		src/orderby.cpp \
		src/sqlitebackupprocessor.cpp \
		src/validators/validator.cpp \
		src/validators/param.cpp \
		src/validators/errormsg.cpp \
		src/validators/defaultvalidator.cpp \
		src/validators/validatorfactory.cpp \
		src/validators/validatorrule.cpp \
		src/validators/requiredvalidator.cpp \
		src/validators/numbervalidator.cpp \
		src/validators/urlvalidator.cpp \
		src/validators/comparevalidator.cpp \
		src/validators/datevalidator.cpp \
		src/validators/emailvalidator.cpp \
		src/validators/existvalidator.cpp \
		src/validators/filevalidator.cpp \
		src/validators/imagevalidator.cpp \
		src/validators/uniquevalidator.cpp \
		src/validators/patternvalidator.cpp \
		src/validators/lengthvalidator.cpp \
		src/schema/mysqlquerybuilder.cpp \
		src/entityinspector.cpp moc_entity.cpp \
		moc_entitymanager.cpp \
		moc_databasemigration.cpp \
		moc_validator.cpp \
		moc_defaultvalidator.cpp \
		moc_requiredvalidator.cpp \
		moc_numbervalidator.cpp \
		moc_urlvalidator.cpp \
		moc_comparevalidator.cpp \
		moc_datevalidator.cpp \
		moc_emailvalidator.cpp \
		moc_existvalidator.cpp \
		moc_filevalidator.cpp \
		moc_imagevalidator.cpp \
		moc_uniquevalidator.cpp \
		moc_patternvalidator.cpp \
		moc_lengthvalidator.cpp
OBJECTS       = entity.o \
		entitymanager.o \
		database.o \
		schema.o \
		sqliteschema.o \
		tableschema.o \
		pgsqlschema.o \
		mysqlschema.o \
		databasemigration.o \
		querybuilder.o \
		sqlitequerybuilder.o \
		relation.o \
		entityinstancefactory.o \
		cache.o \
		entityhelper.o \
		logger.o \
		query.o \
		join.o \
		queryinterpreter.o \
		expression.o \
		orderby.o \
		sqlitebackupprocessor.o \
		validator.o \
		param.o \
		errormsg.o \
		defaultvalidator.o \
		validatorfactory.o \
		validatorrule.o \
		requiredvalidator.o \
		numbervalidator.o \
		urlvalidator.o \
		comparevalidator.o \
		datevalidator.o \
		emailvalidator.o \
		existvalidator.o \
		filevalidator.o \
		imagevalidator.o \
		uniquevalidator.o \
		patternvalidator.o \
		lengthvalidator.o \
		mysqlquerybuilder.o \
		entityinspector.o \
		moc_entity.o \
		moc_entitymanager.o \
		moc_databasemigration.o \
		moc_validator.o \
		moc_defaultvalidator.o \
		moc_requiredvalidator.o \
		moc_numbervalidator.o \
		moc_urlvalidator.o \
		moc_comparevalidator.o \
		moc_datevalidator.o \
		moc_emailvalidator.o \
		moc_existvalidator.o \
		moc_filevalidator.o \
		moc_imagevalidator.o \
		moc_uniquevalidator.o \
		moc_patternvalidator.o \
		moc_lengthvalidator.o
DIST          = README.md \
		LICENSE \
		Doxyfile \
		/usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/sanitize.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_Attica.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivities.pri \
		/usr/lib/qt/mkspecs/modules/qt_KArchive.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuth.pri \
		/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCMUtils.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCrash.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDeclarative.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDESu.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDEWebKit.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDNSSD.pri \
		/usr/lib/qt/mkspecs/modules/qt_KEmoticons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KHtml.pri \
		/usr/lib/qt/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIdleTime.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemModels.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJS.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJSApi.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJsEmbed.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuff.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifyConfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib/qt/mkspecs/modules/qt_KParts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPeople.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPeopleWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPlotting.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPty.pri \
		/usr/lib/qt/mkspecs/modules/qt_KrossCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KrossUi.pri \
		/usr/lib/qt/mkspecs/modules/qt_KRunner.pri \
		/usr/lib/qt/mkspecs/modules/qt_KScreen.pri \
		/usr/lib/qt/mkspecs/modules/qt_KService.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextEditor.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KUnitConversion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWallet.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandClient.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandServer.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_declarative.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_declarative_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_phonon4qt5.pri \
		/usr/lib/qt/mkspecs/modules/qt_Prison.pri \
		/usr/lib/qt/mkspecs/modules/qt_QGpgme.pri \
		/usr/lib/qt/mkspecs/modules/qt_QuickAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_Solid.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib/qt/mkspecs/modules/qt_ThreadWeaver.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/c++11.prf \
		/usr/lib/qt/mkspecs/features/c++14.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		EntityManager.pro src/entity.h \
		src/entitymanager.h \
		src/database.h \
		src/enums/databasetype.h \
		src/schema.h \
		src/schema/sqliteschema.h \
		src/tableschema.h \
		src/schema/pgsqlschema.h \
		src/schema/mysqlschema.h \
		src/databasemigration.h \
		src/querybuilder.h \
		src/schema/sqlitequerybuilder.h \
		src/relation.h \
		src/entityinstancefactory.h \
		src/cache.h \
		src/entityhelper.h \
		src/logger.h \
		src/query.h \
		src/join.h \
		src/queryinterpreter.h \
		src/expression.h \
		src/orderby.h \
		src/sqlitebackupprocessor.h \
		src/validators/validator.h \
		src/validators/param.h \
		src/validators/errormsg.h \
		src/validators/defaultvalidator.h \
		src/validators/validatorfactory.h \
		src/validators/validatorrule.h \
		src/validators/requiredvalidator.h \
		src/validators/numbervalidator.h \
		src/validators/urlvalidator.h \
		src/validators/comparevalidator.h \
		src/validators/datevalidator.h \
		src/validators/emailvalidator.h \
		src/validators/existvalidator.h \
		src/validators/filevalidator.h \
		src/validators/imagevalidator.h \
		src/validators/uniquevalidator.h \
		src/validators/patternvalidator.h \
		src/validators/lengthvalidator.h \
		src/schema/mysqlquerybuilder.h \
		src/entityinspector.h src/entity.cpp \
		src/entitymanager.cpp \
		src/database.cpp \
		src/schema.cpp \
		src/schema/sqliteschema.cpp \
		src/tableschema.cpp \
		src/schema/pgsqlschema.cpp \
		src/schema/mysqlschema.cpp \
		src/databasemigration.cpp \
		src/querybuilder.cpp \
		src/schema/sqlitequerybuilder.cpp \
		src/relation.cpp \
		src/entityinstancefactory.cpp \
		src/cache.cpp \
		src/entityhelper.cpp \
		src/logger.cpp \
		src/query.cpp \
		src/join.cpp \
		src/queryinterpreter.cpp \
		src/expression.cpp \
		src/orderby.cpp \
		src/sqlitebackupprocessor.cpp \
		src/validators/validator.cpp \
		src/validators/param.cpp \
		src/validators/errormsg.cpp \
		src/validators/defaultvalidator.cpp \
		src/validators/validatorfactory.cpp \
		src/validators/validatorrule.cpp \
		src/validators/requiredvalidator.cpp \
		src/validators/numbervalidator.cpp \
		src/validators/urlvalidator.cpp \
		src/validators/comparevalidator.cpp \
		src/validators/datevalidator.cpp \
		src/validators/emailvalidator.cpp \
		src/validators/existvalidator.cpp \
		src/validators/filevalidator.cpp \
		src/validators/imagevalidator.cpp \
		src/validators/uniquevalidator.cpp \
		src/validators/patternvalidator.cpp \
		src/validators/lengthvalidator.cpp \
		src/schema/mysqlquerybuilder.cpp \
		src/entityinspector.cpp
QMAKE_TARGET  = CuteEntityManager
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = libCuteEntityManager.so.1.0.0
TARGETA       = libCuteEntityManager.a
TARGET0       = libCuteEntityManager.so
TARGETD       = libCuteEntityManager.so.1.0.0
TARGET1       = libCuteEntityManager.so.1
TARGET2       = libCuteEntityManager.so.1.0


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	-$(DEL_FILE) $(TARGET) $(TARGET0) $(TARGET1) $(TARGET2)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)
	-ln -s $(TARGET) $(TARGET0)
	-ln -s $(TARGET) $(TARGET1)
	-ln -s $(TARGET) $(TARGET2)



staticlib: $(TARGETA)

$(TARGETA):  $(OBJECTS) $(OBJCOMP) 
	-$(DEL_FILE) $(TARGETA) 
	$(AR) $(TARGETA) $(OBJECTS)

Makefile: EntityManager.pro /usr/lib/qt/mkspecs/linux-g++/qmake.conf /usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/sanitize.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_Attica.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivities.pri \
		/usr/lib/qt/mkspecs/modules/qt_KArchive.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuth.pri \
		/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCMUtils.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCrash.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDeclarative.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDESu.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDEWebKit.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDNSSD.pri \
		/usr/lib/qt/mkspecs/modules/qt_KEmoticons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KHtml.pri \
		/usr/lib/qt/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIdleTime.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemModels.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJS.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJSApi.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJsEmbed.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuff.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifyConfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib/qt/mkspecs/modules/qt_KParts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPeople.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPeopleWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPlotting.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPty.pri \
		/usr/lib/qt/mkspecs/modules/qt_KrossCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KrossUi.pri \
		/usr/lib/qt/mkspecs/modules/qt_KRunner.pri \
		/usr/lib/qt/mkspecs/modules/qt_KScreen.pri \
		/usr/lib/qt/mkspecs/modules/qt_KService.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextEditor.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KUnitConversion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWallet.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandClient.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandServer.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_declarative.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_declarative_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_phonon4qt5.pri \
		/usr/lib/qt/mkspecs/modules/qt_Prison.pri \
		/usr/lib/qt/mkspecs/modules/qt_QGpgme.pri \
		/usr/lib/qt/mkspecs/modules/qt_QuickAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_Solid.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib/qt/mkspecs/modules/qt_ThreadWeaver.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/c++11.prf \
		/usr/lib/qt/mkspecs/features/c++14.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		EntityManager.pro \
		/usr/lib/libQt5Sql.prl \
		/usr/lib/libQt5Core.prl
	$(QMAKE) -o Makefile EntityManager.pro
/usr/lib/qt/mkspecs/features/spec_pre.prf:
/usr/lib/qt/mkspecs/common/unix.conf:
/usr/lib/qt/mkspecs/common/linux.conf:
/usr/lib/qt/mkspecs/common/sanitize.conf:
/usr/lib/qt/mkspecs/common/gcc-base.conf:
/usr/lib/qt/mkspecs/common/gcc-base-unix.conf:
/usr/lib/qt/mkspecs/common/g++-base.conf:
/usr/lib/qt/mkspecs/common/g++-unix.conf:
/usr/lib/qt/mkspecs/qconfig.pri:
/usr/lib/qt/mkspecs/modules/qt_Attica.pri:
/usr/lib/qt/mkspecs/modules/qt_KActivities.pri:
/usr/lib/qt/mkspecs/modules/qt_KArchive.pri:
/usr/lib/qt/mkspecs/modules/qt_KAuth.pri:
/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri:
/usr/lib/qt/mkspecs/modules/qt_KCMUtils.pri:
/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri:
/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KCrash.pri:
/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KDeclarative.pri:
/usr/lib/qt/mkspecs/modules/qt_KDESu.pri:
/usr/lib/qt/mkspecs/modules/qt_KDEWebKit.pri:
/usr/lib/qt/mkspecs/modules/qt_KDNSSD.pri:
/usr/lib/qt/mkspecs/modules/qt_KEmoticons.pri:
/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri:
/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KHtml.pri:
/usr/lib/qt/mkspecs/modules/qt_KI18n.pri:
/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri:
/usr/lib/qt/mkspecs/modules/qt_KIdleTime.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KItemModels.pri:
/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri:
/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KJS.pri:
/usr/lib/qt/mkspecs/modules/qt_KJSApi.pri:
/usr/lib/qt/mkspecs/modules/qt_KJsEmbed.pri:
/usr/lib/qt/mkspecs/modules/qt_KNewStuff.pri:
/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri:
/usr/lib/qt/mkspecs/modules/qt_KNotifyConfig.pri:
/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri:
/usr/lib/qt/mkspecs/modules/qt_KParts.pri:
/usr/lib/qt/mkspecs/modules/qt_KPeople.pri:
/usr/lib/qt/mkspecs/modules/qt_KPeopleWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KPlotting.pri:
/usr/lib/qt/mkspecs/modules/qt_KPty.pri:
/usr/lib/qt/mkspecs/modules/qt_KrossCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KrossUi.pri:
/usr/lib/qt/mkspecs/modules/qt_KRunner.pri:
/usr/lib/qt/mkspecs/modules/qt_KScreen.pri:
/usr/lib/qt/mkspecs/modules/qt_KService.pri:
/usr/lib/qt/mkspecs/modules/qt_KTextEditor.pri:
/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KUnitConversion.pri:
/usr/lib/qt/mkspecs/modules/qt_KWallet.pri:
/usr/lib/qt/mkspecs/modules/qt_KWaylandClient.pri:
/usr/lib/qt/mkspecs/modules/qt_KWaylandServer.pri:
/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri:
/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_clucene_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_declarative.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_declarative_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_help.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_location.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_script.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkit_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_websockets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/lib/qt/mkspecs/modules/qt_phonon4qt5.pri:
/usr/lib/qt/mkspecs/modules/qt_Prison.pri:
/usr/lib/qt/mkspecs/modules/qt_QGpgme.pri:
/usr/lib/qt/mkspecs/modules/qt_QuickAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_Solid.pri:
/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri:
/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri:
/usr/lib/qt/mkspecs/modules/qt_ThreadWeaver.pri:
/usr/lib/qt/mkspecs/features/qt_functions.prf:
/usr/lib/qt/mkspecs/features/qt_config.prf:
/usr/lib/qt/mkspecs/linux-g++/qmake.conf:
/usr/lib/qt/mkspecs/features/spec_post.prf:
/usr/lib/qt/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt/mkspecs/features/default_pre.prf:
/usr/lib/qt/mkspecs/features/resolve_config.prf:
/usr/lib/qt/mkspecs/features/default_post.prf:
/usr/lib/qt/mkspecs/features/c++11.prf:
/usr/lib/qt/mkspecs/features/c++14.prf:
/usr/lib/qt/mkspecs/features/warn_on.prf:
/usr/lib/qt/mkspecs/features/qt.prf:
/usr/lib/qt/mkspecs/features/resources.prf:
/usr/lib/qt/mkspecs/features/moc.prf:
/usr/lib/qt/mkspecs/features/unix/thread.prf:
/usr/lib/qt/mkspecs/features/testcase_targets.prf:
/usr/lib/qt/mkspecs/features/exceptions.prf:
/usr/lib/qt/mkspecs/features/yacc.prf:
/usr/lib/qt/mkspecs/features/lex.prf:
EntityManager.pro:
/usr/lib/libQt5Sql.prl:
/usr/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile EntityManager.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents src/entity.h src/entitymanager.h src/database.h src/enums/databasetype.h src/schema.h src/schema/sqliteschema.h src/tableschema.h src/schema/pgsqlschema.h src/schema/mysqlschema.h src/databasemigration.h src/querybuilder.h src/schema/sqlitequerybuilder.h src/relation.h src/entityinstancefactory.h src/cache.h src/entityhelper.h src/logger.h src/query.h src/join.h src/queryinterpreter.h src/expression.h src/orderby.h src/sqlitebackupprocessor.h src/validators/validator.h src/validators/param.h src/validators/errormsg.h src/validators/defaultvalidator.h src/validators/validatorfactory.h src/validators/validatorrule.h src/validators/requiredvalidator.h src/validators/numbervalidator.h src/validators/urlvalidator.h src/validators/comparevalidator.h src/validators/datevalidator.h src/validators/emailvalidator.h src/validators/existvalidator.h src/validators/filevalidator.h src/validators/imagevalidator.h src/validators/uniquevalidator.h src/validators/patternvalidator.h src/validators/lengthvalidator.h src/schema/mysqlquerybuilder.h src/entityinspector.h $(DISTDIR)/
	$(COPY_FILE) --parents src/entity.cpp src/entitymanager.cpp src/database.cpp src/schema.cpp src/schema/sqliteschema.cpp src/tableschema.cpp src/schema/pgsqlschema.cpp src/schema/mysqlschema.cpp src/databasemigration.cpp src/querybuilder.cpp src/schema/sqlitequerybuilder.cpp src/relation.cpp src/entityinstancefactory.cpp src/cache.cpp src/entityhelper.cpp src/logger.cpp src/query.cpp src/join.cpp src/queryinterpreter.cpp src/expression.cpp src/orderby.cpp src/sqlitebackupprocessor.cpp src/validators/validator.cpp src/validators/param.cpp src/validators/errormsg.cpp src/validators/defaultvalidator.cpp src/validators/validatorfactory.cpp src/validators/validatorrule.cpp src/validators/requiredvalidator.cpp src/validators/numbervalidator.cpp src/validators/urlvalidator.cpp src/validators/comparevalidator.cpp src/validators/datevalidator.cpp src/validators/emailvalidator.cpp src/validators/existvalidator.cpp src/validators/filevalidator.cpp src/validators/imagevalidator.cpp src/validators/uniquevalidator.cpp src/validators/patternvalidator.cpp src/validators/lengthvalidator.cpp src/schema/mysqlquerybuilder.cpp src/entityinspector.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) $(TARGET0) $(TARGET1) $(TARGET2) $(TARGETA)
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_entity.cpp moc_entitymanager.cpp moc_databasemigration.cpp moc_validator.cpp moc_defaultvalidator.cpp moc_requiredvalidator.cpp moc_numbervalidator.cpp moc_urlvalidator.cpp moc_comparevalidator.cpp moc_datevalidator.cpp moc_emailvalidator.cpp moc_existvalidator.cpp moc_filevalidator.cpp moc_imagevalidator.cpp moc_uniquevalidator.cpp moc_patternvalidator.cpp moc_lengthvalidator.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_entity.cpp moc_entitymanager.cpp moc_databasemigration.cpp moc_validator.cpp moc_defaultvalidator.cpp moc_requiredvalidator.cpp moc_numbervalidator.cpp moc_urlvalidator.cpp moc_comparevalidator.cpp moc_datevalidator.cpp moc_emailvalidator.cpp moc_existvalidator.cpp moc_filevalidator.cpp moc_imagevalidator.cpp moc_uniquevalidator.cpp moc_patternvalidator.cpp moc_lengthvalidator.cpp
moc_entity.cpp: src/relation.h \
		src/entityinstancefactory.h \
		src/validators/validatorrule.h \
		src/validators/param.h \
		src/validators/errormsg.h \
		src/entity.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/cehringfeld/gitrepos/entitymanager -I/usr/include/qt -I/usr/include/qt/QtSql -I/usr/include/qt/QtCore -I/usr/include/c++/5.2.0 -I/usr/include/c++/5.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include-fixed -I/usr/include src/entity.h -o moc_entity.cpp

moc_entitymanager.cpp: src/schema.h \
		src/tableschema.h \
		src/querybuilder.h \
		src/relation.h \
		src/expression.h \
		src/query.h \
		src/join.h \
		src/orderby.h \
		src/entity.h \
		src/entityinstancefactory.h \
		src/validators/validatorrule.h \
		src/validators/param.h \
		src/validators/errormsg.h \
		src/database.h \
		src/enums/databasetype.h \
		src/schema/sqliteschema.h \
		src/logger.h \
		src/queryinterpreter.h \
		src/cache.h \
		src/entityhelper.h \
		src/entitymanager.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/cehringfeld/gitrepos/entitymanager -I/usr/include/qt -I/usr/include/qt/QtSql -I/usr/include/qt/QtCore -I/usr/include/c++/5.2.0 -I/usr/include/c++/5.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include-fixed -I/usr/include src/entitymanager.h -o moc_entitymanager.cpp

moc_databasemigration.cpp: src/entity.h \
		src/relation.h \
		src/entityinstancefactory.h \
		src/validators/validatorrule.h \
		src/validators/param.h \
		src/validators/errormsg.h \
		src/databasemigration.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/cehringfeld/gitrepos/entitymanager -I/usr/include/qt -I/usr/include/qt/QtSql -I/usr/include/qt/QtCore -I/usr/include/c++/5.2.0 -I/usr/include/c++/5.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include-fixed -I/usr/include src/databasemigration.h -o moc_databasemigration.cpp

moc_validator.cpp: src/validators/param.h \
		src/validators/errormsg.h \
		src/validators/validator.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/cehringfeld/gitrepos/entitymanager -I/usr/include/qt -I/usr/include/qt/QtSql -I/usr/include/qt/QtCore -I/usr/include/c++/5.2.0 -I/usr/include/c++/5.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include-fixed -I/usr/include src/validators/validator.h -o moc_validator.cpp

moc_defaultvalidator.cpp: src/validators/validator.h \
		src/validators/param.h \
		src/validators/errormsg.h \
		src/validators/defaultvalidator.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/cehringfeld/gitrepos/entitymanager -I/usr/include/qt -I/usr/include/qt/QtSql -I/usr/include/qt/QtCore -I/usr/include/c++/5.2.0 -I/usr/include/c++/5.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include-fixed -I/usr/include src/validators/defaultvalidator.h -o moc_defaultvalidator.cpp

moc_requiredvalidator.cpp: src/validators/validator.h \
		src/validators/param.h \
		src/validators/errormsg.h \
		src/validators/requiredvalidator.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/cehringfeld/gitrepos/entitymanager -I/usr/include/qt -I/usr/include/qt/QtSql -I/usr/include/qt/QtCore -I/usr/include/c++/5.2.0 -I/usr/include/c++/5.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include-fixed -I/usr/include src/validators/requiredvalidator.h -o moc_requiredvalidator.cpp

moc_numbervalidator.cpp: src/validators/validator.h \
		src/validators/param.h \
		src/validators/errormsg.h \
		src/validators/numbervalidator.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/cehringfeld/gitrepos/entitymanager -I/usr/include/qt -I/usr/include/qt/QtSql -I/usr/include/qt/QtCore -I/usr/include/c++/5.2.0 -I/usr/include/c++/5.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include-fixed -I/usr/include src/validators/numbervalidator.h -o moc_numbervalidator.cpp

moc_urlvalidator.cpp: src/validators/validator.h \
		src/validators/param.h \
		src/validators/errormsg.h \
		src/validators/urlvalidator.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/cehringfeld/gitrepos/entitymanager -I/usr/include/qt -I/usr/include/qt/QtSql -I/usr/include/qt/QtCore -I/usr/include/c++/5.2.0 -I/usr/include/c++/5.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include-fixed -I/usr/include src/validators/urlvalidator.h -o moc_urlvalidator.cpp

moc_comparevalidator.cpp: src/validators/validator.h \
		src/validators/param.h \
		src/validators/errormsg.h \
		src/validators/comparevalidator.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/cehringfeld/gitrepos/entitymanager -I/usr/include/qt -I/usr/include/qt/QtSql -I/usr/include/qt/QtCore -I/usr/include/c++/5.2.0 -I/usr/include/c++/5.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include-fixed -I/usr/include src/validators/comparevalidator.h -o moc_comparevalidator.cpp

moc_datevalidator.cpp: src/validators/validator.h \
		src/validators/param.h \
		src/validators/errormsg.h \
		src/validators/datevalidator.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/cehringfeld/gitrepos/entitymanager -I/usr/include/qt -I/usr/include/qt/QtSql -I/usr/include/qt/QtCore -I/usr/include/c++/5.2.0 -I/usr/include/c++/5.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include-fixed -I/usr/include src/validators/datevalidator.h -o moc_datevalidator.cpp

moc_emailvalidator.cpp: src/validators/validator.h \
		src/validators/param.h \
		src/validators/errormsg.h \
		src/validators/emailvalidator.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/cehringfeld/gitrepos/entitymanager -I/usr/include/qt -I/usr/include/qt/QtSql -I/usr/include/qt/QtCore -I/usr/include/c++/5.2.0 -I/usr/include/c++/5.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include-fixed -I/usr/include src/validators/emailvalidator.h -o moc_emailvalidator.cpp

moc_existvalidator.cpp: src/validators/validator.h \
		src/validators/param.h \
		src/validators/errormsg.h \
		src/validators/existvalidator.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/cehringfeld/gitrepos/entitymanager -I/usr/include/qt -I/usr/include/qt/QtSql -I/usr/include/qt/QtCore -I/usr/include/c++/5.2.0 -I/usr/include/c++/5.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include-fixed -I/usr/include src/validators/existvalidator.h -o moc_existvalidator.cpp

moc_filevalidator.cpp: src/validators/validator.h \
		src/validators/param.h \
		src/validators/errormsg.h \
		src/validators/filevalidator.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/cehringfeld/gitrepos/entitymanager -I/usr/include/qt -I/usr/include/qt/QtSql -I/usr/include/qt/QtCore -I/usr/include/c++/5.2.0 -I/usr/include/c++/5.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include-fixed -I/usr/include src/validators/filevalidator.h -o moc_filevalidator.cpp

moc_imagevalidator.cpp: src/validators/filevalidator.h \
		src/validators/validator.h \
		src/validators/param.h \
		src/validators/errormsg.h \
		src/validators/imagevalidator.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/cehringfeld/gitrepos/entitymanager -I/usr/include/qt -I/usr/include/qt/QtSql -I/usr/include/qt/QtCore -I/usr/include/c++/5.2.0 -I/usr/include/c++/5.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include-fixed -I/usr/include src/validators/imagevalidator.h -o moc_imagevalidator.cpp

moc_uniquevalidator.cpp: src/validators/validator.h \
		src/validators/param.h \
		src/validators/errormsg.h \
		src/validators/uniquevalidator.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/cehringfeld/gitrepos/entitymanager -I/usr/include/qt -I/usr/include/qt/QtSql -I/usr/include/qt/QtCore -I/usr/include/c++/5.2.0 -I/usr/include/c++/5.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include-fixed -I/usr/include src/validators/uniquevalidator.h -o moc_uniquevalidator.cpp

moc_patternvalidator.cpp: src/validators/validator.h \
		src/validators/param.h \
		src/validators/errormsg.h \
		src/validators/patternvalidator.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/cehringfeld/gitrepos/entitymanager -I/usr/include/qt -I/usr/include/qt/QtSql -I/usr/include/qt/QtCore -I/usr/include/c++/5.2.0 -I/usr/include/c++/5.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include-fixed -I/usr/include src/validators/patternvalidator.h -o moc_patternvalidator.cpp

moc_lengthvalidator.cpp: src/validators/validator.h \
		src/validators/param.h \
		src/validators/errormsg.h \
		src/validators/lengthvalidator.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/cehringfeld/gitrepos/entitymanager -I/usr/include/qt -I/usr/include/qt/QtSql -I/usr/include/qt/QtCore -I/usr/include/c++/5.2.0 -I/usr/include/c++/5.2.0/x86_64-unknown-linux-gnu -I/usr/include/c++/5.2.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include-fixed -I/usr/include src/validators/lengthvalidator.h -o moc_lengthvalidator.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

entity.o: src/entity.cpp src/entity.h \
		src/relation.h \
		src/entityinstancefactory.h \
		src/validators/validatorrule.h \
		src/validators/param.h \
		src/validators/errormsg.h \
		src/entityhelper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o entity.o src/entity.cpp

entitymanager.o: src/entitymanager.cpp src/entitymanager.h \
		src/schema.h \
		src/tableschema.h \
		src/querybuilder.h \
		src/relation.h \
		src/expression.h \
		src/query.h \
		src/join.h \
		src/orderby.h \
		src/entity.h \
		src/entityinstancefactory.h \
		src/validators/validatorrule.h \
		src/validators/param.h \
		src/validators/errormsg.h \
		src/database.h \
		src/enums/databasetype.h \
		src/schema/sqliteschema.h \
		src/logger.h \
		src/queryinterpreter.h \
		src/cache.h \
		src/entityhelper.h \
		src/databasemigration.h \
		src/validators/validatorfactory.h \
		src/validators/validator.h \
		src/entityinspector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o entitymanager.o src/entitymanager.cpp

database.o: src/database.cpp src/database.h \
		src/enums/databasetype.h \
		src/schema/sqliteschema.h \
		src/schema.h \
		src/tableschema.h \
		src/querybuilder.h \
		src/relation.h \
		src/expression.h \
		src/query.h \
		src/join.h \
		src/orderby.h \
		src/logger.h \
		src/schema/mysqlschema.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o database.o src/database.cpp

schema.o: src/schema.cpp src/schema.h \
		src/tableschema.h \
		src/querybuilder.h \
		src/relation.h \
		src/expression.h \
		src/query.h \
		src/join.h \
		src/orderby.h \
		src/database.h \
		src/enums/databasetype.h \
		src/schema/sqliteschema.h \
		src/logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o schema.o src/schema.cpp

sqliteschema.o: src/schema/sqliteschema.cpp src/schema/sqliteschema.h \
		src/schema.h \
		src/tableschema.h \
		src/querybuilder.h \
		src/relation.h \
		src/expression.h \
		src/query.h \
		src/join.h \
		src/orderby.h \
		src/database.h \
		src/enums/databasetype.h \
		src/logger.h \
		src/schema/sqlitequerybuilder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sqliteschema.o src/schema/sqliteschema.cpp

tableschema.o: src/tableschema.cpp src/tableschema.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tableschema.o src/tableschema.cpp

pgsqlschema.o: src/schema/pgsqlschema.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pgsqlschema.o src/schema/pgsqlschema.cpp

mysqlschema.o: src/schema/mysqlschema.cpp src/schema/mysqlschema.h \
		src/schema.h \
		src/tableschema.h \
		src/querybuilder.h \
		src/relation.h \
		src/expression.h \
		src/query.h \
		src/join.h \
		src/orderby.h \
		src/database.h \
		src/enums/databasetype.h \
		src/schema/sqliteschema.h \
		src/logger.h \
		src/schema/mysqlquerybuilder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mysqlschema.o src/schema/mysqlschema.cpp

databasemigration.o: src/databasemigration.cpp src/databasemigration.h \
		src/entity.h \
		src/relation.h \
		src/entityinstancefactory.h \
		src/validators/validatorrule.h \
		src/validators/param.h \
		src/validators/errormsg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o databasemigration.o src/databasemigration.cpp

querybuilder.o: src/querybuilder.cpp src/querybuilder.h \
		src/relation.h \
		src/expression.h \
		src/query.h \
		src/join.h \
		src/orderby.h \
		src/database.h \
		src/enums/databasetype.h \
		src/schema/sqliteschema.h \
		src/schema.h \
		src/tableschema.h \
		src/logger.h \
		src/entity.h \
		src/entityinstancefactory.h \
		src/validators/validatorrule.h \
		src/validators/param.h \
		src/validators/errormsg.h \
		src/entityhelper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o querybuilder.o src/querybuilder.cpp

sqlitequerybuilder.o: src/schema/sqlitequerybuilder.cpp src/schema/sqlitequerybuilder.h \
		src/querybuilder.h \
		src/relation.h \
		src/expression.h \
		src/query.h \
		src/join.h \
		src/orderby.h \
		src/schema.h \
		src/tableschema.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sqlitequerybuilder.o src/schema/sqlitequerybuilder.cpp

relation.o: src/relation.cpp src/relation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o relation.o src/relation.cpp

entityinstancefactory.o: src/entityinstancefactory.cpp src/entityinstancefactory.h \
		src/entity.h \
		src/relation.h \
		src/validators/validatorrule.h \
		src/validators/param.h \
		src/validators/errormsg.h \
		src/entityhelper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o entityinstancefactory.o src/entityinstancefactory.cpp

cache.o: src/cache.cpp src/cache.h \
		src/entityinstancefactory.h \
		src/entity.h \
		src/relation.h \
		src/validators/validatorrule.h \
		src/validators/param.h \
		src/validators/errormsg.h \
		src/entityhelper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cache.o src/cache.cpp

entityhelper.o: src/entityhelper.cpp src/entityhelper.h \
		src/entity.h \
		src/relation.h \
		src/entityinstancefactory.h \
		src/validators/validatorrule.h \
		src/validators/param.h \
		src/validators/errormsg.h \
		src/cache.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o entityhelper.o src/entityhelper.cpp

logger.o: src/logger.cpp src/logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o logger.o src/logger.cpp

query.o: src/query.cpp src/query.h \
		src/join.h \
		src/expression.h \
		src/orderby.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o query.o src/query.cpp

join.o: src/join.cpp src/join.h \
		src/expression.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o join.o src/join.cpp

queryinterpreter.o: src/queryinterpreter.cpp src/queryinterpreter.h \
		src/join.h \
		src/expression.h \
		src/query.h \
		src/orderby.h \
		src/querybuilder.h \
		src/relation.h \
		src/schema.h \
		src/tableschema.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o queryinterpreter.o src/queryinterpreter.cpp

expression.o: src/expression.cpp src/expression.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o expression.o src/expression.cpp

orderby.o: src/orderby.cpp src/orderby.h \
		src/expression.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o orderby.o src/orderby.cpp

sqlitebackupprocessor.o: src/sqlitebackupprocessor.cpp src/sqlitebackupprocessor.h \
		src/database.h \
		src/enums/databasetype.h \
		src/schema/sqliteschema.h \
		src/schema.h \
		src/tableschema.h \
		src/querybuilder.h \
		src/relation.h \
		src/expression.h \
		src/query.h \
		src/join.h \
		src/orderby.h \
		src/logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sqlitebackupprocessor.o src/sqlitebackupprocessor.cpp

validator.o: src/validators/validator.cpp src/validators/validator.h \
		src/validators/param.h \
		src/validators/errormsg.h \
		src/validators/validatorfactory.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o validator.o src/validators/validator.cpp

param.o: src/validators/param.cpp src/validators/param.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o param.o src/validators/param.cpp

errormsg.o: src/validators/errormsg.cpp src/validators/errormsg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o errormsg.o src/validators/errormsg.cpp

defaultvalidator.o: src/validators/defaultvalidator.cpp src/validators/defaultvalidator.h \
		src/validators/validator.h \
		src/validators/param.h \
		src/validators/errormsg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o defaultvalidator.o src/validators/defaultvalidator.cpp

validatorfactory.o: src/validators/validatorfactory.cpp src/validators/validatorfactory.h \
		src/validators/defaultvalidator.h \
		src/validators/validator.h \
		src/validators/param.h \
		src/validators/errormsg.h \
		src/validators/requiredvalidator.h \
		src/validators/numbervalidator.h \
		src/validators/comparevalidator.h \
		src/validators/emailvalidator.h \
		src/validators/existvalidator.h \
		src/validators/filevalidator.h \
		src/validators/imagevalidator.h \
		src/validators/datevalidator.h \
		src/validators/urlvalidator.h \
		src/validators/uniquevalidator.h \
		src/validators/patternvalidator.h \
		src/validators/lengthvalidator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o validatorfactory.o src/validators/validatorfactory.cpp

validatorrule.o: src/validators/validatorrule.cpp src/validators/validatorrule.h \
		src/validators/param.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o validatorrule.o src/validators/validatorrule.cpp

requiredvalidator.o: src/validators/requiredvalidator.cpp src/validators/requiredvalidator.h \
		src/validators/validator.h \
		src/validators/param.h \
		src/validators/errormsg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o requiredvalidator.o src/validators/requiredvalidator.cpp

numbervalidator.o: src/validators/numbervalidator.cpp src/validators/numbervalidator.h \
		src/validators/validator.h \
		src/validators/param.h \
		src/validators/errormsg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o numbervalidator.o src/validators/numbervalidator.cpp

urlvalidator.o: src/validators/urlvalidator.cpp src/validators/urlvalidator.h \
		src/validators/validator.h \
		src/validators/param.h \
		src/validators/errormsg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o urlvalidator.o src/validators/urlvalidator.cpp

comparevalidator.o: src/validators/comparevalidator.cpp src/validators/comparevalidator.h \
		src/validators/validator.h \
		src/validators/param.h \
		src/validators/errormsg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o comparevalidator.o src/validators/comparevalidator.cpp

datevalidator.o: src/validators/datevalidator.cpp src/validators/datevalidator.h \
		src/validators/validator.h \
		src/validators/param.h \
		src/validators/errormsg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o datevalidator.o src/validators/datevalidator.cpp

emailvalidator.o: src/validators/emailvalidator.cpp src/validators/emailvalidator.h \
		src/validators/validator.h \
		src/validators/param.h \
		src/validators/errormsg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o emailvalidator.o src/validators/emailvalidator.cpp

existvalidator.o: src/validators/existvalidator.cpp src/validators/existvalidator.h \
		src/validators/validator.h \
		src/validators/param.h \
		src/validators/errormsg.h \
		src/entity.h \
		src/relation.h \
		src/entityinstancefactory.h \
		src/validators/validatorrule.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o existvalidator.o src/validators/existvalidator.cpp

filevalidator.o: src/validators/filevalidator.cpp src/validators/filevalidator.h \
		src/validators/validator.h \
		src/validators/param.h \
		src/validators/errormsg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filevalidator.o src/validators/filevalidator.cpp

imagevalidator.o: src/validators/imagevalidator.cpp src/validators/imagevalidator.h \
		src/validators/filevalidator.h \
		src/validators/validator.h \
		src/validators/param.h \
		src/validators/errormsg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imagevalidator.o src/validators/imagevalidator.cpp

uniquevalidator.o: src/validators/uniquevalidator.cpp src/validators/uniquevalidator.h \
		src/validators/validator.h \
		src/validators/param.h \
		src/validators/errormsg.h \
		src/entitymanager.h \
		src/schema.h \
		src/tableschema.h \
		src/querybuilder.h \
		src/relation.h \
		src/expression.h \
		src/query.h \
		src/join.h \
		src/orderby.h \
		src/entity.h \
		src/entityinstancefactory.h \
		src/validators/validatorrule.h \
		src/database.h \
		src/enums/databasetype.h \
		src/schema/sqliteschema.h \
		src/logger.h \
		src/queryinterpreter.h \
		src/cache.h \
		src/entityhelper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o uniquevalidator.o src/validators/uniquevalidator.cpp

patternvalidator.o: src/validators/patternvalidator.cpp src/validators/patternvalidator.h \
		src/validators/validator.h \
		src/validators/param.h \
		src/validators/errormsg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o patternvalidator.o src/validators/patternvalidator.cpp

lengthvalidator.o: src/validators/lengthvalidator.cpp src/validators/lengthvalidator.h \
		src/validators/validator.h \
		src/validators/param.h \
		src/validators/errormsg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lengthvalidator.o src/validators/lengthvalidator.cpp

mysqlquerybuilder.o: src/schema/mysqlquerybuilder.cpp src/schema/mysqlquerybuilder.h \
		src/querybuilder.h \
		src/relation.h \
		src/expression.h \
		src/query.h \
		src/join.h \
		src/orderby.h \
		src/schema.h \
		src/tableschema.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mysqlquerybuilder.o src/schema/mysqlquerybuilder.cpp

entityinspector.o: src/entityinspector.cpp src/entityinspector.h \
		src/entity.h \
		src/relation.h \
		src/entityinstancefactory.h \
		src/validators/validatorrule.h \
		src/validators/param.h \
		src/validators/errormsg.h \
		src/entityhelper.h \
		src/logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o entityinspector.o src/entityinspector.cpp

moc_entity.o: moc_entity.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_entity.o moc_entity.cpp

moc_entitymanager.o: moc_entitymanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_entitymanager.o moc_entitymanager.cpp

moc_databasemigration.o: moc_databasemigration.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_databasemigration.o moc_databasemigration.cpp

moc_validator.o: moc_validator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_validator.o moc_validator.cpp

moc_defaultvalidator.o: moc_defaultvalidator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_defaultvalidator.o moc_defaultvalidator.cpp

moc_requiredvalidator.o: moc_requiredvalidator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_requiredvalidator.o moc_requiredvalidator.cpp

moc_numbervalidator.o: moc_numbervalidator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_numbervalidator.o moc_numbervalidator.cpp

moc_urlvalidator.o: moc_urlvalidator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_urlvalidator.o moc_urlvalidator.cpp

moc_comparevalidator.o: moc_comparevalidator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_comparevalidator.o moc_comparevalidator.cpp

moc_datevalidator.o: moc_datevalidator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_datevalidator.o moc_datevalidator.cpp

moc_emailvalidator.o: moc_emailvalidator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_emailvalidator.o moc_emailvalidator.cpp

moc_existvalidator.o: moc_existvalidator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_existvalidator.o moc_existvalidator.cpp

moc_filevalidator.o: moc_filevalidator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_filevalidator.o moc_filevalidator.cpp

moc_imagevalidator.o: moc_imagevalidator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_imagevalidator.o moc_imagevalidator.cpp

moc_uniquevalidator.o: moc_uniquevalidator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_uniquevalidator.o moc_uniquevalidator.cpp

moc_patternvalidator.o: moc_patternvalidator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_patternvalidator.o moc_patternvalidator.cpp

moc_lengthvalidator.o: moc_lengthvalidator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_lengthvalidator.o moc_lengthvalidator.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/usr/lib || mkdir -p $(INSTALL_ROOT)/usr/lib
	-$(INSTALL_PROGRAM) $(TARGET) $(INSTALL_ROOT)/usr/lib/$(TARGET)
	-$(STRIP) --strip-unneeded $(INSTALL_ROOT)/usr/lib/$(TARGET)
	-$(SYMLINK) $(TARGET) $(INSTALL_ROOT)/usr/lib/$(TARGET0)
	-$(SYMLINK) $(TARGET) $(INSTALL_ROOT)/usr/lib/$(TARGET1)
	-$(SYMLINK) $(TARGET) $(INSTALL_ROOT)/usr/lib/$(TARGET2)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/usr/lib/$(TARGET) 
	 -$(DEL_FILE) $(INSTALL_ROOT)/usr/lib/$(TARGET0) 
	 -$(DEL_FILE) $(INSTALL_ROOT)/usr/lib/$(TARGET1) 
	 -$(DEL_FILE) $(INSTALL_ROOT)/usr/lib/$(TARGET2)
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/lib/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

